#pragma once

// Generated by scripts/generate_footer_icons_from_image.py.
// Edit the source PNG/PBM assets and manifest instead of hand-tuning rows here.

namespace lofi_board::footer_icons {

static const char *const kNoteRows[] = {
    "......######....",
    "......##..##....",
    "......##..##....",
    "......##..##....",
    "......##..##....",
    "......##..##....",
    "..######..##....",
    ".#######.###....",
    "######..####....",
    "#####...###.....",
    ".###.....#......",
    "..#.............",
};
static constexpr int kNoteX = 10;
static constexpr int kNoteY = 121;

static const char *const kSpeakerRows[] = {
    "................",
    "....##..........",
    "...###...#......",
    "..####....#.....",
    ".#####.....#....",
    "######..#...#...",
    "######..#...#...",
    ".#####.....#....",
    "..####....#.....",
    "...###...#......",
    "....##..........",
    "................",
};
static constexpr int kSpeakerX = 113;
static constexpr int kSpeakerY = 121;

static const char *const kRepeatRows[] = {
    ".........##.....",
    "........####....",
    "..###########...",
    "..##....####....",
    "..##.....##.....",
    "................",
    "................",
    ".....##.....##..",
    "....####....##..",
    "...###########..",
    "....####........",
    ".....##.........",
};
static constexpr int kRepeatX = 146;
static constexpr int kRepeatY = 121;

static const char *const kQueueRows[] = {
    "................",
    "###########.....",
    "###########.....",
    "................",
    "##########...#..",
    "##########...#..",
    "............###.",
    "##########...#..",
    "##########...#..",
    "................",
    "................",
    "................",
};
static constexpr int kQueueX = 218;
static constexpr int kQueueY = 121;

} // namespace lofi_board::footer_icons
