#!/usr/bin/env python3
"""Generate fixed-size 1-bit volume icon masks from SVG assets."""

from __future__ import annotations

import subprocess
import tempfile
from pathlib import Path

from PIL import Image


ROOT = Path(__file__).resolve().parents[1]
SOURCE_DIR = ROOT / "assets" / "volume_icons"
OUT = ROOT / "main" / "lofi_volume_icons.hpp"
TARGET_W = 18
TARGET_H = 12

ICONS = [
    ("Mute", "ion-volume-off.svg"),
    ("Low", "ion-volume-low.svg"),
    ("Medium", "ion-volume-medium.svg"),
    ("High", "ion-volume-high.svg"),
]


def render_svg(svg: Path, png: Path) -> None:
    subprocess.run(
        [
            "rsvg-convert",
            "-w",
            "128",
            "-h",
            "128",
            str(svg),
            "-o",
            str(png),
        ],
        check=True,
    )


def mask_rows(svg: Path) -> list[str]:
    with tempfile.TemporaryDirectory() as tmp:
        png = Path(tmp) / "icon.png"
        render_svg(svg, png)
        image = Image.open(png).convert("RGBA")

    alpha = image.getchannel("A")
    bbox = alpha.getbbox()
    if bbox is None:
        raise ValueError(f"{svg}: empty icon")
    alpha = alpha.crop(bbox)

    src_w, src_h = alpha.size
    scale = min(TARGET_W / src_w, TARGET_H / src_h)
    dst_w = max(1, round(src_w * scale))
    dst_h = max(1, round(src_h * scale))
    resized = alpha.resize((dst_w, dst_h), Image.Resampling.LANCZOS)

    canvas = Image.new("L", (TARGET_W, TARGET_H), 0)
    canvas.paste(resized, ((TARGET_W - dst_w) // 2, (TARGET_H - dst_h) // 2))
    pixels = canvas.load()
    rows = []
    for y in range(TARGET_H):
        row = []
        for x in range(TARGET_W):
            alpha = pixels[x, y]
            if alpha < 24:
                row.append(".")
            elif alpha < 96:
                row.append(":")
            elif alpha < 176:
                row.append("+")
            else:
                row.append("#")
        rows.append("".join(row))
    return rows


def write_header(icons: list[tuple[str, list[str]]]) -> None:
    lines = [
        "#pragma once",
        "",
        "// Generated by scripts/generate_volume_icons.py.",
        "// Edit assets/volume_icons/*.svg and regenerate instead of hand-tuning rows.",
        "// Pixel levels: '.' transparent, ':' low opacity, '+' medium opacity, '#' solid.",
        "",
        "namespace lofi_board::volume_icons {",
        "",
    ]
    for name, rows in icons:
        lines.append(f"static const char *const k{name}Rows[] = {{")
        for row in rows:
            lines.append(f'    "{row}",')
        lines.append("};")
        lines.append("")
    lines.append(f"static constexpr int kWidth = {TARGET_W};")
    lines.append(f"static constexpr int kHeight = {TARGET_H};")
    lines.append("")
    lines.append("} // namespace lofi_board::volume_icons")
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    icons = []
    for name, filename in ICONS:
        svg = SOURCE_DIR / filename
        if not svg.exists():
            raise FileNotFoundError(svg)
        icons.append((name, mask_rows(svg)))
    write_header(icons)


if __name__ == "__main__":
    main()
